### ISSUE TITLE
Bookmaker

### ISSUE THREAD

**Issue by bhousel** [bhousel/temaki#17]
for `shop=bookmaker`
(good luck with this one)

**Comment by matkoniecz** [comment]
There is https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/shop/bookmaker.svg

Not great but may be useful at least as an inspiration.

**Comment by bhousel** [comment]
Yeah, I saw it.. don't really understand it though 🤔

**Comment by matkoniecz** [comment]
It is supposed to be combination of ticket + clover as symbol of luck/randomness (though using 3-leaf variant instead of 4-leaf variant is quite ironic, it may make even less likely that someone will understand it).

Maybe dice would be more clear?

**Comment by bhousel** [comment]
I made a "money hand" icon that we can use for this (and maybe other stuff).. 💸 

<img width="164" alt="Screenshot 2019-09-25 14 52 07" src="https://user-images.githubusercontent.com/38784/65630786-11eebd00-dfa4-11e9-92e9-d387caa6047e.png">
