### ISSUE TITLE
Coffee beans

### ISSUE THREAD

**Issue by bhousel** [bhousel/temaki#34]
for `shop=coffee`  (not `amenity=cafe`)

**Comment by quincylvania** [comment]
OSM-carto has a [decent icon for this](https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/shop/coffee.svg).

Related: https://github.com/openstreetmap/iD/issues/6606

**Comment by bhousel** [comment]
Cool, I started with the carto one and scaled it up and cleaned up the paths in 2165102
