### ISSUE TITLE
Transit/parking ticket vending machine

### ISSUE THREAD

**Issue by quincylvania** [bhousel/temaki#35]
These thing are really [more like terminals](https://i1.wp.com/farm3.static.flickr.com/2066/2277927150_ea09132416_o.jpg) and don't fit the icon for vending "stuff".

<img width="334" alt="Screen Shot 2019-10-02 at 7 29 25 PM" src="https://user-images.githubusercontent.com/2046746/66067061-1b9b9600-e54b-11e9-8dba-f8f4cf7e6c56.png">

**Comment by bhousel** [comment]
yeah I had the idea that I might make a few more kinds of vending machines.. I did draw a newspaper one, but that's mostly just because they have such a different shape.
