### ISSUE TITLE
Bleachers

### ISSUE THREAD

**Issue by quincylvania** [bhousel/temaki#36]
For [leisure=bleachers](https://wiki.openstreetmap.org/wiki/Tag%3Aleisure%3Dbleachers).

When I first started mapping I didn't think this was even a "real" tag since it didn't have an icon and didn't render in OSM carto.

<img width="211" alt="Screen Shot 2019-10-02 at 7 32 01 PM" src="https://user-images.githubusercontent.com/2046746/66067185-5bfb1400-e54b-11e9-9a90-85cd27ec4e41.png">

**Comment by bhousel** [comment]
This one was really challenging 😂 
<img width="165" alt="Screenshot 2019-10-04 16 22 14" src="https://user-images.githubusercontent.com/38784/66237422-08133b00-e6c3-11e9-8fb2-d20b6db14202.png">

**Comment by quincylvania** [comment]
@bhousel Thanks! Looks good. Yeah I tried to do make one awhile back and failed, who would have thought this would be so difficult? 😅
