### ISSUE TITLE
Water Tower

### ISSUE THREAD

**Issue by quincylvania** [bhousel/temaki#42]
iD overuses the droplet icon already. These also have a distinctive shape so it'd be nice to use that to show how these are different from from simple water storage tanks.

<img width="685" alt="Screen Shot 2019-11-13 at 3 41 18 PM" src="https://user-images.githubusercontent.com/2046746/68802570-28bca200-062c-11ea-8833-2782ceb8d2d8.png">

**Comment by bhousel** [comment]
oh yeah good suggestion 👍
